import type { Metadata } from "next";
import { montserrat } from "@/fonts/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat} antialiased bg-gradient-to-r dark:from-[#ff8800] dark:via-[#c0012a] dark:to-[#940533] from-[#ffb300] to-[#c0012a] via-[#ff8800]`}
      >
        {children}
      </body>
    </html>
  );
}
